### ISSUE TITLE
Error to run App

### ISSUE THREAD

**Issue by FabricioMedeiros** [LiveLikeCounter/Flutter-Todolist#3]
Hi, I'm new to Flutter development, and I found your app beautiful, I would like to try it out and see the features. But I went to run the app and the following error occurred:

* Error running Gradle:
ProcessException: Process "D:\Projetos\flutter\Exemplos\Flutter_Todolist\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projetos\flutter\Exemplos\Flutter_Todolist\android\app\build.gradle' line: 53

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

How can I resolve this ?

**Comment by LiveLikeCounter** [comment]
Hi, I saw your issues a bit late. But the problem is that the "build.gradle" contains the production signing. I just replace that with the debug. 

Can you pull the repo and test it again?

**Comment by LiveLikeCounter** [comment]
No response, closing issue
