### ISSUE TITLE
 Error to run App 

### ISSUE THREAD

**Issue by ZedKi7** [LiveLikeCounter/Flutter-Todolist#8]
I went to run the app and the following error occurred:

Launching lib/main.dart on sdk gphone x86 arm in debug mode...
../../flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:407:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);
                                                        ^^^^^^
../../flutter/packages/flutter/lib/src/material/scaffold.dart:1944:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {

                       ^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/gradient_app_bar-0.1.3/lib/gradient_app_bar.dart:636:20: Error: The method 'ancestorRenderObjectOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorRenderObjectOfType'.
    return context.ancestorRenderObjectOfType(

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.
* Where:
Script '/home/zedki7/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/zedki7/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by LiveLikeCounter** [comment]
Hi @ZedKi7 , thank you for mentioning this one.
I'll investigate. It has probably to do with the `gradient_app_bar` package.

**Comment by LiveLikeCounter** [comment]
It's fixed
